### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by tonghae** [sitegui/nodejs-websocket#24] opened 2015-12-02 06:22 UTC
Greetings! Getting this on Chrome.
Any workaround? Thanks.

**Comment by sitegui** [comment] 2015-12-17 08:31
Hi @tonghae 

I tried to reproduce this in my machine, but it worked fine (tested in current Firefox and Chrome).

Could you please provide more context on what you trying to do? A sample code that reproduces this or the error's stack trace would help.

**Comment by sitegui** [comment] 2016-01-10 15:05
Since no one else reported this and I couldn't reproduce this, I'm closing this issue.

If you face this problem again, feel free to report in a new one ;)

**Comment by Sinkthor** [comment] 2016-08-16 13:30
Hi I'm having the same issue...
`WebSocket connection to 'ws://localhost:3000/mqtt' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

Do you have a tip?

**Comment by sitegui** [comment] 2016-08-16 13:56
Hi @Sinkthor 

Do you mind sharing an example of a code that triggers this error (both server and client-side)?

I recall a PR from @padarom trying to fix this, but I don't remember what happened to that. I'll look into this later tomorrow.

**Comment by Sinkthor** [comment] 2016-08-16 14:03
Thank you for your help and time!!
I'm using the Chrome extension -> MQTT2Chrome as my client.
I think the problem might be from this code section:
`var WebSocketServer = require('websocket').server;
wsServer = new WebSocketServer({
  httpServer: server});

wsServer.on('request', function(request){
  var connection = request.accept(null, request.origin);
  console.log("CONNECTED AGAIN");
  connection.on('message', function(message){
    console.log('Received Message: ' +message);
    console.log('OR Received Message: ' + message.utf8Data);
    connection.send(message);
    connection.sendUTF(message.utf8Data);});});`

**Comment by sitegui** [comment] 2016-08-17 04:04
The issue is, you're using a feature (namely `Sec-WebSocket-Protocol`) not implemented by this module at this time.

It was in my mind for a while. I may take some time this week to put this together.

In fact, some discussion already took place on #30 , but the author closed the issue and I've forgot it.

**Comment by Sinkthor** [comment] 2016-08-17 09:26
I also have this problem when I compile the code... I think  it's relate.
Error: Uncaught, unspecified "error" event. (server sent no subprotocol even though requested)
    at WebSocket.emit (events.js:144:17)
    at ClientRequest.upgrade (C:\Users\User\Desktop\RaphaelClc\Notification\node
_modules\ws\lib\WebSocket.js:757:12)
    at ClientRequest.g (events.js:260:16)
    at emitThree (events.js:97:13)
    at ClientRequest.emit (events.js:175:7)
    at Socket.socketOnData (_http_client.js:336:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)

**Comment by VoidVolker** [comment] 2016-08-18 13:46
Fixed: waiting for PR approving.

**Comment by sitegui** [comment] 2016-09-10 18:52
I've just added support for protocol negotiation in v1.7.0, published to NPM

Thanks for all the help ;)

**Closed by sitegui** 2016-09-10 18:52 UTC
Labels: enhancement
