### ISSUE TITLE
connection.readyState is always 1

### ISSUE THREAD

**Issue by cagdasdoner** [sitegui/nodejs-websocket#38] opened 2016-08-16 15:17 UTC
Hi there,
My websock server runs well but when I check readyState of my disconnected devices they are still assigned as 1.

What am I missing to do?

Thanks pal.

**Comment by sitegui** [comment] 2016-08-16 16:00
Hi @cagdasdoner,

`Connection#readyState` has [four values](https://github.com/sitegui/nodejs-websocket/blob/master/Connection.js#L111-L121) and the code seems to correctly assign it.

Could you share some code reproducing this behavior you're seeing?

**Comment by cagdasdoner** [comment] 2016-08-17 08:33
Hi,

I have multiple nodes that connected to this websocket server. But when I powered off one of them, its connection is shown as still alive. Also I was expected to having a connection close event but I do not know if it is defined in RFC or not. 

So, to an easy check, I prepared a code below : 

```
function WSCheckStatus()
{
    var index = 1;
    WSServer.connections.forEach(function (conn) {
        console.log(index + ". state is : " + conn.readyState);
        index ++;
    })
}

var genericTimer = setInterval(WSCheckStatus, 10000);
```

Where server is **_WSServer_**.

But, I am always getting the ready state as below despite I power off the device : 

ubuntu@ip-172-31-40-238:~/iot/websoc$ node websocs.js 
Received -> {"origin":"device","type":"ws_init","deviceId":1093699}
1. state is : 1
1. state is : 1
Received -> {"type":"switch","deviceId":"1093699","origin":"userclient"}
1. state is : 1
2. state is : 1
1. state is : 1
2. state is : 1
1. state is : 1
2. state is : 1
1. state is : 1
2. state is : 1
1. state is : 1
2. state is : 1
....

**Comment by sitegui** [comment] 2016-09-10 19:00
It's probably due to the TCP's way of handling connections.

Have you tried something like [`socket.setKeepAlive(true, 30e3)`](https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay) and [`socket.setTimeout(30e3)`](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback)?
With this, the TCP will send probes (ping/pong packages) every 30s and you can then use the `'timeout'` event to close the connection

**Closed** 2016-11-02 11:07 UTC
